### ISSUE TITLE
Lecture "Computability", exercise 2

### ISSUE THREAD

**Issue by essepuntato** [comp-think/2024-2025#10]
Consider an algorithm that takes as input a 0-1 sequence of exactly five symbols and returns 1 if the sequence contains at least three **consecutive** _1s_, and returns 0 otherwise. Implement the algorithm with a Turing machine, where the cell corresponding to the starting position of the head is where the final result must be stored. Also, the five cells following the starting position of the head are initialised with the 0-1 sequence of five symbols used as input of the algorithm.

**Comment by KikaYang** [comment]
input: '000111'
blank: ' '
start state: start
table:
  start:
    0: {R: A}
    1: {R: A}
  A:
    0: {write: 0, R: B}
    1: {write: 1, R: }
  B:
    0: {write: 0, R: C}
    1: {write: 1, R: }
  C:
    0: {write: 0, L: D}
    1: {write: 1, R: E}
  D:
  E:
    0: {write: 0, L: }
    1: {write: 1, R: F}
  F:
    0: {write: 0, L: }
    1: {write: 1, L: G}
  G:
    0: {L: H}
    1: {L: H}
  H:
    0: {L: I}
    1: {L: I}
  I:
    0: {L: J}
    1: {L: J}
  J:
    0: {L: K}
    1: {L: K}
  K:
    0: {write: 1, L: DONE}
    1: {write: 1, L: DONE}
  DONE:

My original intention was to program based on a state tree (all possible combinations), but through continuous debugging, I was only able to keep the part of the code that 'generates results based on the output. Sorry about that.

**Comment by ValkyrieCain9** [comment]
I made the algorithm so it was considering three numbers at a time before looping on itself, this allowed me to reduce to number of states I would need to account for. 

input: '11011'
blank: ' '
start state: step
table:
  #step forward to check middle of group of three
  step:
    [0,1] : {R: checkM}
    ' ': {L: result0}
  
  #check middle
  checkM:
    0 : R
    1 : {L: checkL}
    ' ': {L: result0}
  
  #check number left of middle
  checkL:
    0 : {R: step} 
    1 : {R: yes1}
  
  #if 1 is found on the left and middle check the right  
  yes1:
    1 : {R: checkR}
  
  #check number right of middle
  checkR:
    0: {L: step}
    1: {L: result1}
    ' ': {L: result0}
  
  #move back to the start of the sequence and print result 0 for no consecutive 1s found
  result0:
    [0,1] : L
    ' ' : {write: 0, L: done}
  
  #move back to the start of the sequence and print result 1 for three consecutive 1s found
  result1:
    [0,1] : L
    ' ' : {write: 1, L: done}
 
 done: 
<img width="812" alt="Screenshot 2024-10-29 at 16 28 58" src="https://github.com/user-attachments/assets/4a224c53-921a-4417-a478-49f754eeaef9">

<img width="797" alt="Screenshot 2024-10-29 at 16 29 25" src="https://github.com/user-attachments/assets/ffa27962-43e2-41d9-a072-f0f07c983c98">

**Comment by ERendall** [comment]
Naturally, as the very slow one suffering the trauma of previously burying my head in too many history books, I am in a state of awe as to how you did this. 

I presume that the head is limited to one move either right of left at any time. So, how did you manage to move the head back to the start of the sequence in one step? 

Could you elaborate, hammering it into my thick skull? 😂

**Comment by theair-hub** [comment]
My algorithm uses six cells 'cause I considered the starting position as not part of the original 5 symbols, since you wrote "the five cells following the starting position [...]". This should work also with more than 5 symbols! 

input: 'x00000'
blank: ' '
start state: start

table:
  start: 
    'x': {R: q1}
  q0: 
    [0, 1]: L
    'x': {write: 0, L:}
  q1:
    '1': {R: q2}
    '0': {R: q1}
    ' ': {L: q0}
  q2:
    '1': {R: q3}
    '0': {R: q1}
    ' ': {L: q0}
  q3: 
    '1': {L: q4}
    '0': {R: q1}
    ' ': {L: q0}
  q4: 
    [0, 1]: L
    'x': {write: 1, L}
done:

**Comment by theair-hub** [comment]
> Naturally, as the very slow one suffering the trauma of previously burying my head in too many history books, I am in a state of awe as to how you did this.
> 
> I presume that the head is limited to one move either right of left at any time. So, how did you manage to move the head back to the start of the sequence in one step?
> 
> Could you elaborate, hammering it into my thick skull? 😂

That's fine, that was my initial problem too! At the beginning, I tried to write an algorithm that started with moving my 0 state (not the starting one!, that I called 'start') to the right until blank was found (i.e. the last cell, the one after the 5 symbols), in order to develop an algorithm that didn't- let's say- "moved" on the right, but backwards, so it returned to the starting position, cause it literally started from the last symbol. 

table:
  start: 
    'x': {R: q0}            #go right to the "q0" state
  q0: 
    [0, 1]: R              #if you see 0 or 1, then continue to go right...
    ' ' : {L: q1}           #... until you find blank, then go left (backwards!) and finally start the algorithm with the first state, currently 
                                    working on the last cell.
  q1:
[...]

Of course, while I wrote the rest I specified the Left (L:) position. You can try like this.

But then, I didn't think that was the fastest route xD so I suggest you an algorithm that whenever finds blank (so the end of the five symbols) should return to a state that specifies to go- again, just like before- to the Left whenever a 0 or a 1 is found, until he finds what I called "x", the starting position. Maybe it is not very clear like that, but I suggest you to copy and paste what I wrote on turingmachine.io so maybe it's simpler to understand it since there is a visual representation :/ (supposing that what I wrote is correct, as I hope, lol).

**Comment by ERendall** [comment]
… I think it may be best if you explain this to me in person… 😂

**Comment by ERendall** [comment]
We still have the problem of ‘going again’ — how does one, after completing the fifth step of the algorithm, step back five paces to begin again? 

I am trying a cyclical solution, ferrying results via decision widgets into a cache (if you can call it that). But the tape restricts me, unless I am mistaken in thinking the Turing Machine has no cache memory…!

**Comment by ValkyrieCain9** [comment]
I do not believe the machine has memory so you cannot use an algorithm that stores a result until the end like we could under normal circumstances. Because of this you need to think about how to use what would have been the "stored result" at a way to move the head to the next state. Also with this in mind, by the time the head has reached the end of the sequence it should have checked all the numbers already

**Comment by theair-hub** [comment]
Sorry about that, maybe I can try with adding comments:

input: 'x00000' #x is the starting position where the result will be stored; then, the other 5 symbol you can put any sequence of 
                        1 and 0
blank: ' '
start state: start

table:
start:
'x': {R: q1} #starting from x, go right to begin the "actual" algorithm

q1:
'1': {R: q2} #if there is 1...good! Check the q2command. 
'0': {R: q1} #if there is 0, then you should go back to the q1 command and start again checking *the cell on the right*
' ': {L: q0} #if you are on a blank cell, then the 5 symbol sequence is over, so go read the commands written in q0 

q2:
'1': {R: q3} #if there is another 1...good! check the q3command. 
'0': {R: q1} #if there is 0, then you should go back to the q1 command and start again checking *the cell on the right*
' ': {L: q0} #if you are on a blank cell, that means that the 5 symbol sequence is over, so go read the commands written in q0 

q3:
'1': {L: q4} #if there is another 1...good! You found three *1s* in a row. Check the q4 command. 
'0': {R: q1} #if there is 0, then you should go back to the q1 command and start again but *on the cell on the right*
' ': {L: q0} #but if you are on a blank cell, that means that the 5 symbol sequence is over, so go read the commands written in q0

q4: #The command that determines how to go back to the starting position and write 1.
[0, 1]: L #whenever you see 0 or 1, go right
'x': {write: 1, L} #once you reached the "x" (aka the starting position), write 1, cause you found three consecutive *1s*

q0: #The command that determines how to go back to the starting position and write 0.
[0, 1]: L #since you are at the end of the 5 symbols, go left anytime you see 0 and 1 
'x': {write: 0, L:} #once you reach x (aka the starting point), write the result: 0 

Of course, if you try a better way to do that, feel free to let me know! I hope this helps understanding what I wrote <3


> We still have the problem of ‘going again’ — how does one, after completing the fifth step of the algorithm, step back five paces to begin again?
> 
> I am trying a cyclical solution, ferrying results via decision widgets into a cache (if you can call it that). But the tape restricts me, unless I am mistaken in thinking the Turing Machine has no cache memory…!


> … I think it may be best if you explain this to me in person… 😂

**Comment by yutong316** [comment]
![image](https://github.com/user-attachments/assets/7d770428-2f88-4081-838d-e2a7d8e25e6f)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/27815/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/27815/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D" lang=ZH-CN>


Current State | Current   Symbol | Write   Symbol | Move   Direction | Next   State
-- | -- | -- | -- | --
A | 0 | 0 | right | A
A | 1 | 1 | right | B
B | 0 | 0 | left | F
B | 1 | 1 | right | C
C | 0 | 0 | left | F
C | 1 | 1 | right | D
D | 0 | 0 | left | E
D | 1 | 1 | left | E
E | 0 or 1 | 0 or 1 | End | End
F | 0 or 1 | 0 or 1 | End | End



</body>

</html>

**Comment by ERendall** [comment]
<img width="1454" alt="Screenshot 2024-11-10 at 16 08 02" src="https://github.com/user-attachments/assets/6ce58f91-b684-4b75-bbb7-1a5e0247c90c">

Strewth, this bodes well for the future...

**Comment by ERendall** [comment]
<img width="1457" alt="Screenshot 2024-11-10 at 16 32 11" src="https://github.com/user-attachments/assets/df4495d3-7f1f-4bbd-ae41-75884ca9abd8">

Sorry . . . sent something through earlier, but after some debugging, I had to make one or two corrections to deal with an inconsistency.

**Comment by ERendall** [comment]
<img width="1464" alt="Screenshot 2024-11-12 at 09 25 34" src="https://github.com/user-attachments/assets/a6e26ae8-56f2-4f46-b79b-563ec6aec18a">

Here is my revised algorithm for exercise 2. It may look a bit overkill, but it seems solid and reliable after debugging....

The solution was simpler than I thought, admittedly: I decided to provide states representing each of the forms that the string could take, checking each digit in a rigorous fashion. 

To prevent any ambiguities as far as the output was concerned, I re-wrote each digit as 0 after examination, re-writing the first digit (the result) as either 1 or 0 at the end of the process. 

So, a single 1 among a stream of 0s confirmed the presence of consecutive 1s, and an unchanged stream of 0s suggested that no consecutive 1s were found. 

I hope that makes sense…! Happy to chat if not!

**Comment by martinaucch** [comment]
After monday lesson I have tried to tackle again this exercise keeping in mind that the first possibile sequence of digit to get 1 as an output are: 00111, 11100, 01110 as professor peroni said. This time it was easier to come up with a solution. I worked only with 2 digit, setting the blank state to '0'. I think its working... i gave it a few test. as an input though the first digit must be a 0 and the rest are the actual input sequence. If i understood right during the lesson i think thats should be okay cause this is an implementation of the algorithm in the turing machine so we need to work with the concept of the starting state and blank 0. 
```
input: '011001'
blank: '0'
start state: start
table: 
  start:
    0: {write: 1, R: firstcheck}
    1: {write: 0, L: end}

  firstcheck:
    0: {write: 0, R: secondcheck}
    1: {write: 0, R: secondcheck2}
    
  secondcheck:
    0: {write: 0, R: thirdcheck}
    1: {write: 0, R: thirdcheck3}
    
  secondcheck2:
    1: {write: 0, R: thirdcheck2}
    0: {write: 0, L: failed}
  
  thirdcheck:
    0: {write: 0, L: failed}
    1: {write: 0, R: fourthcheck}
    
  thirdcheck2: 
    1: {write: 0, L: end}
    0: {write: 0, L: failed}
    
  thirdcheck3:
    1: {write: 0, R: fourthcheck3}
    0: {write: 0, L: failed}
     
  failed: 
    0: {write: 0, L: failed}
    1: {write: 0, L: end}
    
  fourthcheck: 
    0: {write: 0, L: failed}
    1: {write: 0, R: fifthcheck}
  
  fourthcheck3: 
    1: {write: 0, R: end}
    0: {write: 0, L: failed}
  
  fifthcheck:
    0: {write: 0, L: failed}
    1: {write: 0, R: end}
  
  end:
```
<img width="1433" alt="Screenshot 2024-11-12 alle 19 28 28" src="https://github.com/user-attachments/assets/59f2736e-2bde-4ad9-add0-27cb5289b776">
